In [36]:
pip install -U fortran-magic

Requirement already up-to-date: fortran-magic in /usr/local/lib/python3.6/dist-packages (0.7)


In [37]:
%matplotlib inline
%load_ext fortranmagic

import sys; sys.path.append('..')
import py_compile

import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

mpl.rc('figure', figsize=(12, 7))

ran_the_first_cell = True

jan2017 = pd.to_datetime(['2017-01-03 00:00:00+00:00',
 '2017-01-04 00:00:00+00:00',
 '2017-01-05 00:00:00+00:00',
 '2017-01-06 00:00:00+00:00',
 '2017-01-09 00:00:00+00:00',
 '2017-01-10 00:00:00+00:00',
 '2017-01-11 00:00:00+00:00',
 '2017-01-12 00:00:00+00:00',
 '2017-01-13 00:00:00+00:00',
 '2017-01-17 00:00:00+00:00',
 '2017-01-18 00:00:00+00:00',
 '2017-01-19 00:00:00+00:00',
 '2017-01-20 00:00:00+00:00',
 '2017-01-23 00:00:00+00:00',
 '2017-01-24 00:00:00+00:00',
 '2017-01-25 00:00:00+00:00',
 '2017-01-26 00:00:00+00:00',
 '2017-01-27 00:00:00+00:00',
 '2017-01-30 00:00:00+00:00',
 '2017-01-31 00:00:00+00:00',
 '2017-02-01 00:00:00+00:00'])
calendar = jan2017.values.astype('datetime64[D]')

event_dates = pd.to_datetime(['2017-01-06 00:00:00+00:00', 
                             '2017-01-07 00:00:00+00:00', 
                             '2017-01-08 00:00:00+00:00']).values.astype('datetime64[D]')
event_values = np.array([10, 15, 20])

/usr/local/lib/python3.6/dist-packages/fortranmagic.py:147: UserWarning: get_ipython_cache_dir has moved to the IPython.paths module since IPython 4.0.
  self._lib_dir = os.path.join(get_ipython_cache_dir(), 'fortran')


/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [38]:
fechasEventos = np.array([5,6,7])

<center>
  <h1>The PyData Toolbox</h1>
  <h3>Scott Sanderson (Twitter: @scottbsanderson, GitHub: ssanderson)</h3>
  <h3><a href="https://github.com/ssanderson/pydata-toolbox">https://github.com/ssanderson/pydata-toolbox</a></h3>
</center>

# About Me:

<img src="images/me.jpg" alt="Drawing" style="width: 300px;"/>

- Senior Engineer at [Quantopian](www.quantopian.com)
- Background in Mathematics and Philosophy
- **Twitter:** [@scottbsanderson](https://twitter.com/scottbsanderson)
- **GitHub:** [ssanderson](github.com/ssanderson)

## Outline

- Built-in Data Structures
- Numpy `array`
- Pandas `Series`/`DataFrame`
- Plotting and "Real-World" Analyses

# Data Structures

> Rule 5. Data dominates. If you've chosen the right data structures and organized things well, the algorithms
will almost always be self-evident. Data structures, not algorithms, are central to programming.

- *Notes on Programming in C*, by Rob Pike.

# Lists

In [39]:
assert ran_the_first_cell, "Oh noes!"

In [40]:
assert ran_the_first_cell, "pues no pone nada"

In [41]:
l = [1, 'two', 3.0, 4, 5.0, "six"]
l

[1, 'two', 3.0, 4, 5.0, 'six']

In [42]:
ll = [1,2,3,"tri",4.0,"s", True]
ll

[1, 2, 3, 'tri', 4.0, 's', True]

In [43]:
# Lists can be indexed like C-style arrays.
first = l[0]
second = l[1]
print("first:", first)
print("second:", second)

first: 1
second: two


In [44]:
primero = ll[0]
segundo = ll[1]
print("Primero:", primero)
print("Segundo:", segundo)

Primero: 1
Segundo: 2


In [45]:
# Negative indexing gives elements relative to the end of the list.
last = l[-1]
penultimate = l[-2]
print("last:", last)
print("second to last:", penultimate)

last: six
second to last: 5.0


In [46]:
ultimo = ll[-1]
penultimo = ll[-2]
print("ultimo:", ultimo)
print("penultimo:", penultimo)

ultimo: True
penultimo: s


In [47]:
# Lists can also be sliced, which makes a copy of elements between 
# start (inclusive) and stop (exclusive)
sublist = l[1:3]
sublist

['two', 3.0]

In [48]:
subll = ll[0:2]
subll

[1, 2]

In [49]:
# l[:N] is equivalent to l[0:N].
first_three = l[:3]
first_three

[1, 'two', 3.0]

In [50]:
primerosDos = l[:2]
primerosDos

[1, 'two']

In [51]:
# l[3:] is equivalent to l[3:len(l)].
after_three = l[3:]
after_three

[4, 5.0, 'six']

In [52]:
todo = ll[1:]
todo

[2, 3, 'tri', 4.0, 's', True]

In [53]:
# There's also a third parameter, "step", which gets every Nth element.
l = ['a', 'b', 'c', 'd', 'e', 'f', 'g','h']
l[1:7:2]

['b', 'd', 'f']

In [54]:
ll = [1,2,3,4,5,6,7,8,9,10,11]
ll[0::2]

[1, 3, 5, 7, 9, 11]

In [55]:
# This is a cute way to reverse a list.
l[::-1]

['h', 'g', 'f', 'e', 'd', 'c', 'b', 'a']

In [56]:
ll[::-1]

[11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

In [57]:
# Lists can be grown efficiently (in O(1) amortized time).
l = [1, 2, 3, 4, 5]
print("Before:", l)
l.append('six')
print("After:", l)

Before: [1, 2, 3, 4, 5]
After: [1, 2, 3, 4, 5, 'six']


In [58]:
ll = [1, 2, 3, 4, 5,6,7,8,9,10]
print("Antes:", ll)
ll.append(11)
print("Despues:", ll)

Antes: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
Despues: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


In [59]:
# Comprehensions let us perform elementwise computations.
l = [1, 2, 3, 4, 5]
[x * 2 for x in l]

[2, 4, 6, 8, 10]

In [60]:
ll = [1, 2, 3, 4, 5,0,1,2,3]
[x % 2 for x in ll]

[1, 0, 1, 0, 1, 0, 1, 0, 1]

## Review: Python Lists

- Zero-indexed sequence of arbitrary Python values.
- Slicing syntax: `l[start:stop:step]` copies elements at regular intervals from `start` to `stop`.
- Efficient (`O(1)`) appends and removes from end.
- Comprehension syntax: `[f(x) for x in l if cond(x)]`.

# Dictionaries

In [61]:
# Dictionaries are key-value mappings.
philosophers = {'David': 'Hume', 'Immanuel': 'Kant', 'Bertrand': 'Russell'}
philosophers

{'Bertrand': 'Russell', 'David': 'Hume', 'Immanuel': 'Kant'}

In [62]:
llaves = {'1': 'uno', '2': 'dos', '3': 'tres'}
llaves

{'1': 'uno', '2': 'dos', '3': 'tres'}

In [63]:
# Like lists, dictionaries are size-mutable.
philosophers['Ludwig'] = 'Wittgenstein'
philosophers

{'Bertrand': 'Russell',
 'David': 'Hume',
 'Immanuel': 'Kant',
 'Ludwig': 'Wittgenstein'}

In [64]:
llaves['3'] = "tres"
llaves

{'1': 'uno', '2': 'dos', '3': 'tres'}

In [65]:
del philosophers['David']
philosophers

{'Bertrand': 'Russell', 'Immanuel': 'Kant', 'Ludwig': 'Wittgenstein'}

In [66]:
del llaves['1']
llaves

{'2': 'dos', '3': 'tres'}

In [67]:
# No slicing.
#philosophers['Bertrand':'Immanuel']

## Review: Python Dictionaries

- Unordered key-value mapping from (almost) arbitrary keys to arbitrary values.
- Efficient (`O(1)`) lookup, insertion, and deletion.
- No slicing (would require a notion of order).

<center><img src="images/pacino.gif" alt="Drawing" style="width: 100%;"/></center>


In [68]:
# Suppose we have some matrices...
a = [[1, 2, 3],
     [2, 3, 4],
     [5, 6, 7],
     [1, 1, 1]]

b = [[1, 2, 3, 4],
     [2, 3, 4, 5]]

In [69]:
c = [[1, 2, 3],
     [3, 4, 5],
     [6, 7, 8]
     ]

d = [[1, 2, 3, 4]]

In [70]:
def matmul(A, B):
    """Multiply matrix A by matrix B."""
    rows_out = len(A)
    cols_out = len(B[0])
    out = [[0 for col in range(cols_out)] for row in range(rows_out)]
    
    for i in range(rows_out):
        for j in range(cols_out):
            for k in range(len(B)):
                out[i][j] += A[i][k] * B[k][j]
    return out

In [71]:
def matmul(A, B):
    """Multiply matrix A by matrix B."""
    rows_out = len(A)
    cols_out = len(B[0])
    out = [[0 for col in range(cols_out)] for row in range(rows_out)]
    
    for i in range(rows_out):
        for j in range(cols_out):
            for k in range(len(B)):
                out[i][j] += A[i][k] * B[k][j]
    return out

In [72]:
def miMatMul(a,b):
  filas = len(a)
  columnas = len(b[0])
  output = [[0 for col in range(columnas)] for fil in range(filas)]

  for i in range(filas):
    for j in range(columnas):
      for k in range(len(b)):
        output[i][j] += a[i][k] * b[k][j]
  return output

In [73]:
%%time

matmul(a, b)

CPU times: user 35 µs, sys: 0 ns, total: 35 µs
Wall time: 38.9 µs


[[5, 8, 11, 14], [8, 13, 18, 23], [17, 28, 39, 50], [3, 5, 7, 9]]

In [74]:
miMatMul(c,d)

[[1, 2, 3, 4], [3, 6, 9, 12], [6, 12, 18, 24]]

In [75]:
import random
def random_matrix(m, n):
    out = []
    for row in range(m):
        out.append([random.random() for _ in range(n)])
    return out

randm = random_matrix(2, 3)
randm

[[0.5174373827614807, 0.9051142673039521, 0.42981595860051813],
 [0.0679030118668057, 0.6824232747370202, 0.1598248179448749]]

In [76]:
def miRandomMatrix(m, n):
    out = []
    for row in range(m):
        out.append([random.random() for _ in range(n)])
    return out

miRandm = miRandomMatrix(5, 3)
miRandm

[[0.8695226255816993, 0.5903792762687227, 0.9133435268165265],
 [0.5066461450092017, 0.900706827015827, 0.9935482626394337],
 [0.19784923130604237, 0.35307127699788987, 0.7893715498668772],
 [0.059711484777227875, 0.5668239450340083, 0.9465694154295968],
 [0.14033250492420324, 0.8241284248041094, 0.1020157236874869]]

In [77]:
%%time
randa = random_matrix(600, 100)
randb = random_matrix(100, 600)
x = matmul(randa, randb)

CPU times: user 6.91 s, sys: 8.09 ms, total: 6.92 s
Wall time: 6.93 s


In [78]:
miRanda = miRandomMatrix(600, 200)
miRandb = miRandomMatrix(200, 100)
zz = matmul(randa, randb)

In [79]:
# Maybe that's not that bad?  Let's try a simpler case.
def python_dot_product(xs, ys):
    return sum(x * y for x, y in zip(xs, ys))

In [80]:
def miPythonDotProduct(xs, ys):
    return sum(x * y for x, y in zip(xs, ys))

In [81]:
%%fortran
subroutine fortran_dot_product(xs, ys, result)
    double precision, intent(in) :: xs(:)
    double precision, intent(in) :: ys(:)
    double precision, intent(out) :: result
    
    result = sum(xs * ys)
end

In [82]:
list_data = [float(i) for i in range(100000)]
array_data = np.array(list_data)

In [83]:
listaDatos = [float(i) for i in range(500000)]
arrayDatos = np.array(listaDatos)

In [84]:
%%time
python_dot_product(list_data, list_data)

CPU times: user 8.82 ms, sys: 0 ns, total: 8.82 ms
Wall time: 9.21 ms


333328333350000.0

In [85]:
miPythonDotProduct(listaDatos, listaDatos)

4.16665416666264e+16

In [86]:
%%time
fortran_dot_product(array_data, array_data)

CPU times: user 193 µs, sys: 8 µs, total: 201 µs
Wall time: 235 µs


333328333350000.0

In [87]:
fortran_dot_product(arrayDatos, arrayDatos)

4.16665416666264e+16

<center><img src="images/sloth.gif" alt="Drawing" style="width: 1080px;"/></center>


## Why is the Python Version so Much Slower?

In [88]:
# Dynamic typing.
def mul_elemwise(xs, ys):
    return [x * y for x, y in zip(xs, ys)]

mul_elemwise([1, 2, 3, 4], [1, 2 + 0j, 3.0, 'four'])
#[type(x) for x in _]

[1, (4+0j), 9.0, 'fourfourfourfour']

In [89]:
def mul_elemwise(xs, ys):
    return [x * y for x, y in zip(xs, ys)]

mul_elemwise([1, 2, 3, 4], ["a", "le" + "te", "3.0", 4])

['a', 'letelete', '3.03.03.0', 16]

In [90]:
# Interpretation overhead.
source_code = 'a + b * c'
bytecode = compile(source_code, '', 'eval')
import dis; dis.dis(bytecode)

  1           0 LOAD_NAME                0 (a)
              2 LOAD_NAME                1 (b)
              4 LOAD_NAME                2 (c)
              6 BINARY_MULTIPLY
              8 BINARY_ADD
             10 RETURN_VALUE


## Why is the Python Version so Slow?
- Dynamic typing means that every single operation requires dispatching on the input type.
- Having an interpreter means that every instruction is fetched and dispatched at runtime.
- Other overheads:
  - Arbitrary-size integers.
  - Reference-counted garbage collection.

> This is the paradox that we have to work with when we're doing scientific or numerically-intensive Python. What makes Python fast for development -- this high-level, interpreted, and dynamically-typed aspect of the language -- is exactly what makes it slow for code execution.

- Jake VanderPlas, [*Losing Your Loops: Fast Numerical Computing with NumPy*](https://www.youtube.com/watch?v=EEUXKG97YRw)

# What Do We Do?

- Python is slow for numerical computation because it performs dynamic dispatch on every operation we perform...

- ...but often, we just want to do the same thing over and over in a loop!

- If we don't need Python's dynamicism, we don't want to pay (much) for it.

- **Idea:** Dispatch **once per operation** instead of **once per element**.

In [91]:
import numpy as np

data = np.array([1, 2, 3, 4])
data

array([1, 2, 3, 4])

In [92]:
datos = np.array([3,4,5,7])
datos

array([3, 4, 5, 7])

In [93]:
data + data

array([2, 4, 6, 8])

In [94]:
datos + datos

array([ 6,  8, 10, 14])

In [95]:
%%time
# Naive dot product
(array_data * array_data).sum()

CPU times: user 481 µs, sys: 0 ns, total: 481 µs
Wall time: 490 µs


333328333350000.0

In [96]:
(arrayDatos*arrayDatos).sum()

4.166654166675e+16

In [97]:
%%time
# Built-in dot product.
array_data.dot(array_data)

CPU times: user 1.01 ms, sys: 6.97 ms, total: 7.99 ms
Wall time: 8.71 ms


333328333350000.0

In [98]:
arrayDatos.dot(arrayDatos)

4.166654166675e+16

In [99]:
%%time
fortran_dot_product(array_data, array_data)

CPU times: user 175 µs, sys: 7 µs, total: 182 µs
Wall time: 191 µs


333328333350000.0

In [100]:
fortran_dot_product(arrayDatos, arrayDatos)

4.16665416666264e+16

In [101]:
# Numpy won't allow us to write a string into an int array.
# data[0] = "foo"

In [102]:
# We also can't grow an array once it's created.
#data.append(3)

In [103]:
# We **can** reshape an array though.
two_by_two = data.reshape(2, 2)
two_by_two

array([[1, 2],
       [3, 4]])

In [104]:
dospordos = datos.reshape(2, 2)
dospordos 

array([[3, 4],
       [5, 7]])

Numpy arrays are:

- Fixed-type

- Size-immutable

- Multi-dimensional

- Fast\*

\* If you use them correctly.

# What's in an Array?

In [105]:
arr = np.array([1, 2, 3, 4, 5, 6], dtype='int16').reshape(2, 3)
print("Array:\n", arr, sep='')
print("===========")
print("DType:", arr.dtype)
print("Shape:", arr.shape)
print("Strides:", arr.strides)
print("Data:", arr.data.tobytes())

Array:
[[1 2 3]
 [4 5 6]]
DType: int16
Shape: (2, 3)
Strides: (6, 2)
Data: b'\x01\x00\x02\x00\x03\x00\x04\x00\x05\x00\x06\x00'


In [106]:
auxArr = np.array([1, 2, 3, 4, 5, 6,7,8,9], dtype='int16').reshape(3, 3)
print("Array:\n", arr, sep='')

print("tipo:", arr.dtype)
print("dimensiones:", arr.shape)
print("Strides:", arr.strides)
print("Datos:", arr.data.tobytes())

Array:
[[1 2 3]
 [4 5 6]]
tipo: int16
dimensiones: (2, 3)
Strides: (6, 2)
Datos: b'\x01\x00\x02\x00\x03\x00\x04\x00\x05\x00\x06\x00'


# Core Operations

- Vectorized **ufuncs** for elementwise operations.
- Fancy indexing and masking for selection and filtering.
- Aggregations across axes.
- Broadcasting

# UFuncs

UFuncs (universal functions) are functions that operate elementwise on one or more arrays.

In [107]:
data = np.arange(15).reshape(3, 5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [108]:
datos = np.arange(20).reshape(4, 5)
datos

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [109]:
# Binary operators.
data * data

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196]])

In [110]:
datos * datos

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361]])

In [111]:
# Unary functions.
np.sqrt(data)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739]])

In [112]:
np.sqrt(datos)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739],
       [3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894]])

In [113]:
# Comparison operations
(data % 3) == 0

array([[ True, False, False,  True, False],
       [False,  True, False, False,  True],
       [False, False,  True, False, False]])

In [114]:
(datos % 3) == 0

array([[ True, False, False,  True, False],
       [False,  True, False, False,  True],
       [False, False,  True, False, False],
       [ True, False, False,  True, False]])

In [115]:
# Boolean combinators.
((data % 2) == 0) & ((data % 3) == 0)

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False]])

In [116]:
((datos % 2) == 0) & ((datos % 3) == 0)

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False],
       [False, False, False,  True, False]])

In [117]:
# as of python 3.5, @ is matrix-multiply
data @ data.T

array([[ 30,  80, 130],
       [ 80, 255, 430],
       [130, 430, 730]])

In [118]:
datos @ datos.T

array([[  30,   80,  130,  180],
       [  80,  255,  430,  605],
       [ 130,  430,  730, 1030],
       [ 180,  605, 1030, 1455]])

# UFuncs Review

- UFuncs provide efficient elementwise operations applied across one or more arrays.
- Arithmetic Operators (`+`, `*`, `/`)
- Comparisons (`==`, `>`, `!=`)
- Boolean Operators (`&`, `|`, `^`)
- Trigonometric Functions (`sin`, `cos`)
- Transcendental Functions (`exp`, `log`)

# Selections

We often want to perform an operation on just a subset of our data.

In [119]:
sines = np.sin(np.linspace(0, 3.14, 10))
cosines = np.cos(np.linspace(0, 3.14, 10))
sines

array([0.        , 0.34185385, 0.64251645, 0.86575984, 0.98468459,
       0.98496101, 0.8665558 , 0.64373604, 0.34335012, 0.00159265])

In [120]:
senos = np.sin(np.linspace(0, 3.14, 20))
cosenos = np.cos(np.linspace(0, 3.14, 20))
senos

array([0.        , 0.16451191, 0.3245409 , 0.47572622, 0.61394808,
       0.73543998, 0.83689129, 0.91553747, 0.96923543, 0.99652191,
       0.99665336, 0.96962621, 0.91617692, 0.837762  , 0.73651822,
       0.61520446, 0.4771265 , 0.32604693, 0.16608265, 0.00159265])

In [121]:
# Slicing works with the same semantics as Python lists.
sines[0]

0.0

In [122]:
senos[1]

0.16451190907780003

In [123]:
sines[:3]  # First three elements  

array([0.        , 0.34185385, 0.64251645])

In [124]:
cosenos[:5]

array([1.        , 0.9863751 , 0.94587166, 0.87959341, 0.78934641])

In [125]:
sines[5:]  # Elements from 5 on.

array([0.98496101, 0.8665558 , 0.64373604, 0.34335012, 0.00159265])

In [126]:
cosenos[5:]

array([ 0.67758987,  0.54736914,  0.4022327 ,  0.2461355 ,  0.08333116,
       -0.08174394, -0.24459154, -0.40077406, -0.54603556, -0.67641771,
       -0.7883676 , -0.87883463, -0.94535358, -0.98611184, -0.99999873])

In [127]:
sines[::2]  # Every other element.

array([0.        , 0.64251645, 0.98468459, 0.8665558 , 0.34335012])

In [128]:
senos[::3]

array([0.        , 0.47572622, 0.83689129, 0.99652191, 0.91617692,
       0.61520446, 0.16608265])

In [129]:
# More interesting: we can index with boolean arrays to filter by a predicate.
print("sines:\n", sines)
print("sines > 0.5:\n", sines > 0.5)
print("sines[sines > 0.5]:\n", sines[sines > 0.5])

sines:
 [0.         0.34185385 0.64251645 0.86575984 0.98468459 0.98496101
 0.8665558  0.64373604 0.34335012 0.00159265]
sines > 0.5:
 [False False  True  True  True  True  True  True False False]
sines[sines > 0.5]:
 [0.64251645 0.86575984 0.98468459 0.98496101 0.8665558  0.64373604]


In [130]:
print("senos:\n", senos)
print("cosenos:\n", cosenos)
print("cosenos>0.6:\n", cosenos>0.6)

senos:
 [0.         0.16451191 0.3245409  0.47572622 0.61394808 0.73543998
 0.83689129 0.91553747 0.96923543 0.99652191 0.99665336 0.96962621
 0.91617692 0.837762   0.73651822 0.61520446 0.4771265  0.32604693
 0.16608265 0.00159265]
cosenos:
 [ 1.          0.9863751   0.94587166  0.87959341  0.78934641  0.67758987
  0.54736914  0.4022327   0.2461355   0.08333116 -0.08174394 -0.24459154
 -0.40077406 -0.54603556 -0.67641771 -0.7883676  -0.87883463 -0.94535358
 -0.98611184 -0.99999873]
cosenos>0.6:
 [ True  True  True  True  True  True False False False False False False
 False False False False False False False False]


In [131]:
# We index with lists/arrays of integers to select values at those indices.
print(sines)
sines[[0, 4, 7]]

[0.         0.34185385 0.64251645 0.86575984 0.98468459 0.98496101
 0.8665558  0.64373604 0.34335012 0.00159265]


array([0.        , 0.98468459, 0.64373604])

In [132]:
print(senos)
senos[[0,1,-1]]

[0.         0.16451191 0.3245409  0.47572622 0.61394808 0.73543998
 0.83689129 0.91553747 0.96923543 0.99652191 0.99665336 0.96962621
 0.91617692 0.837762   0.73651822 0.61520446 0.4771265  0.32604693
 0.16608265 0.00159265]


array([0.        , 0.16451191, 0.00159265])

In [133]:
# Index arrays are often used for sorting one or more arrays.
unsorted_data = np.array([1, 3, 2, 12, -1, 5, 2])

In [134]:
datosDesordenados = np.array([5,7,6,13,4,79,2,14])

In [135]:
sort_indices = np.argsort(unsorted_data)
sort_indices

array([4, 0, 2, 6, 1, 5, 3])

In [136]:
indicesOrdenados = np.argsort(datosDesordenados)
indicesOrdenados

array([6, 4, 0, 2, 1, 3, 7, 5])

In [137]:
unsorted_data[sort_indices]

array([-1,  1,  2,  2,  3,  5, 12])

In [138]:
datosDesordenados[indicesOrdenados]


array([ 2,  4,  5,  6,  7, 13, 14, 79])

In [139]:
market_caps = np.array([12, 6, 10, 5, 6])  # Presumably in dollars?
assets = np.array(['A', 'B', 'C', 'D', 'E'])

In [140]:
maximaMercado = np.array([6,1,13,4,8])
bienes = np.array(["q","e","r","t","y"])

In [141]:
# Sort assets by market cap by using the permutation that would sort market caps on ``assets``.
sort_by_mcap = np.argsort(market_caps)
assets[sort_by_mcap]

array(['D', 'B', 'E', 'C', 'A'], dtype='<U1')

In [142]:
ordenarPorMaxima = np.argsort(maximaMercado)
bienes[ordenarPorMaxima]

array(['e', 't', 'q', 'y', 'r'], dtype='<U1')

In [143]:
# Indexers are also useful for aligning data.
print("Dates:\n", repr(event_dates))
print("Values:\n", repr(event_values))
print("Calendar:\n", repr(calendar))

Dates:
 array(['2017-01-06', '2017-01-07', '2017-01-08'], dtype='datetime64[D]')
Values:
 array([10, 15, 20])
Calendar:
 array(['2017-01-03', '2017-01-04', '2017-01-05', '2017-01-06',
       '2017-01-09', '2017-01-10', '2017-01-11', '2017-01-12',
       '2017-01-13', '2017-01-17', '2017-01-18', '2017-01-19',
       '2017-01-20', '2017-01-23', '2017-01-24', '2017-01-25',
       '2017-01-26', '2017-01-27', '2017-01-30', '2017-01-31',
       '2017-02-01'], dtype='datetime64[D]')


In [144]:
print("Fechas:\n", repr(fechasEventos))
print("Valores:\n", repr(event_values))
print("Calendario:\n", repr(calendar))

Fechas:
 array([5, 6, 7])
Valores:
 array([10, 15, 20])
Calendario:
 array(['2017-01-03', '2017-01-04', '2017-01-05', '2017-01-06',
       '2017-01-09', '2017-01-10', '2017-01-11', '2017-01-12',
       '2017-01-13', '2017-01-17', '2017-01-18', '2017-01-19',
       '2017-01-20', '2017-01-23', '2017-01-24', '2017-01-25',
       '2017-01-26', '2017-01-27', '2017-01-30', '2017-01-31',
       '2017-02-01'], dtype='datetime64[D]')


In [145]:
print("Raw Dates:", event_dates)
print("Indices:", calendar.searchsorted(event_dates))
print("Forward-Filled Dates:", calendar[calendar.searchsorted(event_dates)])

Raw Dates: ['2017-01-06' '2017-01-07' '2017-01-08']
Indices: [3 4 4]
Forward-Filled Dates: ['2017-01-06' '2017-01-09' '2017-01-09']


In [146]:
print("Fechas sin editar:", fechasEventos)
print("Indices:", calendar.searchsorted(event_dates))
print("Forward-Filled Dates:", calendar[calendar.searchsorted(event_dates)])

Fechas sin editar: [5 6 7]
Indices: [3 4 4]
Forward-Filled Dates: ['2017-01-06' '2017-01-09' '2017-01-09']


On multi-dimensional arrays, we can slice along each axis independently.

In [147]:
data = np.arange(25).reshape(5, 5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [148]:
datos = np.arange(36).reshape(6,6)

In [149]:
data[:2, :2]  # First two rows and first two columns.

array([[0, 1],
       [5, 6]])

In [150]:
datos[:3,:3]

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [151]:
data[:2, [0, -1]]  # First two rows, first and last columns.

array([[0, 4],
       [5, 9]])

In [152]:
datos[:2,[1,2]]

array([[1, 2],
       [7, 8]])

In [153]:
data[(data[:, 0] % 2) == 0]  # Rows where the first column is divisible by two.

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [154]:
datos[(datos[:,0] %3 ) == 0]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

# Selections Review

- Indexing with an integer removes a dimension.
- Slicing operations work on Numpy arrays the same way they do on lists.
- Indexing with a boolean array filters to True locations.
- Indexing with an integer array selects indices along an axis.
- Multidimensional arrays can apply selections independently along different axes.

## Reductions

Functions that reduce an array to a scalar.

$Var(X) = \frac{1}{N}\sqrt{\sum_{i=1}^N (x_i - \bar{x})^2}$

In [155]:
def variance(x):
    return ((x - x.mean()) ** 2).sum() / len(x)

In [156]:
variance(np.random.standard_normal(1000))

0.9822846959385413

In [157]:
variance(np.random.standard_normal(2000))

0.9909157300629242

- `sum()` and `mean()` are both **reductions**.

- In the simplest case, we use these to reduce an entire array into a single value...

In [158]:
data = np.arange(30)
data.mean()

14.5

In [159]:
datos = np.arange(50)
datos.mean()

24.5

- ...but we can do more interesting things with multi-dimensional arrays.

In [160]:
data = np.arange(30).reshape(3, 10)
data

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [161]:
datos = np.arange(50).reshape(25,2)

In [162]:
data.mean()

14.5

In [163]:
datos.mean()

24.5

In [164]:
data.mean(axis=0)

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19.])

In [165]:
datos.mean(axis=0)

array([24., 25.])

In [166]:
data.mean(axis=1)

array([ 4.5, 14.5, 24.5])

In [167]:
datos.mean(axis=1)

array([ 0.5,  2.5,  4.5,  6.5,  8.5, 10.5, 12.5, 14.5, 16.5, 18.5, 20.5,
       22.5, 24.5, 26.5, 28.5, 30.5, 32.5, 34.5, 36.5, 38.5, 40.5, 42.5,
       44.5, 46.5, 48.5])

## Reductions Review

- Reductions allow us to perform efficient aggregations over arrays.
- We can do aggregations over a single axis to collapse a single dimension.
- Many built-in reductions (`mean`, `sum`, `min`, `max`, `median`, ...).

# Broadcasting

In [168]:
row = np.array([1, 2, 3, 4])
column = np.array([[1], [2], [3]])
print("Row:\n", row, sep='')
print("Column:\n", column, sep='')

Row:
[1 2 3 4]
Column:
[[1]
 [2]
 [3]]


In [169]:
fila = np.array([5,6,7,8,9])
columna = np.array= [[10],[11],[12],[13]]
print("fila:\n",fila,sep='|')
print("Columna:\n", columna,sep="")

fila:
|[5 6 7 8 9]
Columna:
[[10], [11], [12], [13]]


In [170]:
row + column

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

In [171]:
fila + columna

array([[15, 16, 17, 18, 19],
       [16, 17, 18, 19, 20],
       [17, 18, 19, 20, 21],
       [18, 19, 20, 21, 22]])

<center><img src="images/broadcasting.png" alt="Drawing" style="width: 60%;"/></center>

<h5>Source: http://www.scipy-lectures.org/_images/numpy_broadcasting.png</h5>

In [172]:
# Broadcasting is particularly useful in conjunction with reductions.
print("Data:\n", data, sep='')
print("Mean:\n", data.mean(axis=0), sep='')
print("Data - Mean:\n", data - data.mean(axis=0), sep='')

Data:
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]
Mean:
[10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
Data - Mean:
[[-10. -10. -10. -10. -10. -10. -10. -10. -10. -10.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [ 10.  10.  10.  10.  10.  10.  10.  10.  10.  10.]]


In [173]:
print("Datos:\n", datos, sep='')
print("Media:\n", datos.mean(axis=0), sep='')
print("Datos - Media:\n", datos - datos.mean(axis=0), sep='')

Datos:
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]
 [24 25]
 [26 27]
 [28 29]
 [30 31]
 [32 33]
 [34 35]
 [36 37]
 [38 39]
 [40 41]
 [42 43]
 [44 45]
 [46 47]
 [48 49]]
Media:
[24. 25.]
Datos - Media:
[[-24. -24.]
 [-22. -22.]
 [-20. -20.]
 [-18. -18.]
 [-16. -16.]
 [-14. -14.]
 [-12. -12.]
 [-10. -10.]
 [ -8.  -8.]
 [ -6.  -6.]
 [ -4.  -4.]
 [ -2.  -2.]
 [  0.   0.]
 [  2.   2.]
 [  4.   4.]
 [  6.   6.]
 [  8.   8.]
 [ 10.  10.]
 [ 12.  12.]
 [ 14.  14.]
 [ 16.  16.]
 [ 18.  18.]
 [ 20.  20.]
 [ 22.  22.]
 [ 24.  24.]]


# Broadcasting Review

- Numpy operations can work on arrays of different dimensions as long as the arrays' shapes are still "compatible".
- Broadcasting works by "tiling" the smaller array along the missing dimension.
- The result of a broadcasted operation is always at least as large in each dimension as the largest array in that dimension.

# Numpy Review

- Numerical algorithms are slow in pure Python because the overhead dynamic dispatch dominates our runtime.

- Numpy solves this problem by:
  1. Imposing additional restrictions on the contents of arrays.
  2. Moving the inner loops of our algorithms into compiled C code.

- Using Numpy effectively often requires reworking an algorithms to use vectorized operations instead of for-loops, but the resulting operations are usually simpler, clearer, and faster than the pure Python equivalent.

Numpy is great for many things, but...

- Sometimes our data is equipped with a natural set of **labels**:
  - Dates/Times
  - Stock Tickers
  - Field Names (e.g. Open/High/Low/Close)

- Sometimes we have **more than one type of data** that we want to keep grouped together.
  - Tables with a mix of real-valued and categorical data.

- Sometimes we have **missing** data, which we need to ignore, fill, or otherwise work around.

Pandas extends Numpy with more complex data structures:

- `Series`: 1-dimensional, homogenously-typed, labelled array.
- `DataFrame`: 2-dimensional, semi-homogenous, labelled table.

Pandas also provides many utilities for: 
- Input/Output
- Data Cleaning
- Rolling Algorithms
- Plotting

# Selection in Pandas

In [174]:
import pandas as pd

s = pd.Series(index=['a','b','c','d'], data=[1,2,3,4])
s

TypeError: ignored

In [ ]:
data = [1,2,3,4,5]

seleccion = pd.Series(data, index=[100,101,102,103,1])
seleccion



In [ ]:
# There are two pieces to a Series: the index and the values.
print("The index is:")
print("The values are:")

In [ ]:
# We can look up values out of a Series by position...

s.iloc[0]

In [ ]:
seleccion.iloc[0]

In [ ]:
# ... or by label.
s.loc['a']

In [ ]:
seleccion.loc[1]

In [ ]:
# Slicing works as expected...
s.iloc[:2]

In [ ]:
seleccion.iloc[:2]

In [ ]:
# ...but it works with labels too!
s.loc[:'c']

In [ ]:
seleccion.loc[:1]

In [ ]:
# Fancy indexing works the same as in numpy.
s.iloc[[0, -1]]

In [ ]:
seleccion.iloc[[0, -2]]

In [ ]:
# As does boolean masking.
s.loc[s > 2]

In [ ]:
seleccion[seleccion>2]

In [ ]:
# Element-wise operations are aligned by index.
other_s = pd.Series({'a': 10.0, 'c': 20.0, 'd': 30.0, 'z': 40.0})
other_s

In [ ]:
otraSeleccion = pd.Series({'1': 10.0, 'c2': 20.0, '3': 30.0, 'z': 40.0})
otraSeleccion

In [ ]:
s + other_s

In [ ]:
seleccion + otraSeleccion

In [ ]:
# We can fill in missing values with fillna().
(s + other_s).fillna(0.0)

In [ ]:
(seleccion + otraSeleccion).fillna(0.0)

In [ ]:
# Most real datasets are read in from an external file format.
aapl = pd.read_csv('AAPL.csv', parse_dates=['Date'], index_col='Date')
aapl.head()

In [175]:
apple = pd.read_csv('AAPL.csv', parse_dates=['Date'], index_col='Date')
apple.head()

FileNotFoundError: ignored

In [176]:
# Slicing generalizes to two dimensions as you'd expect:
aapl.iloc[:2, :2]

NameError: ignored

In [177]:
apple.iloc[:3, :2]

NameError: ignored

In [178]:
aapl.loc[pd.Timestamp('2010-02-01'):pd.Timestamp('2010-02-04'), ['Close', 'Volume']]

NameError: ignored

In [179]:
apple.loc[pd.Timestamp('2010-02-30'):pd.Timestamp('2010-02-31'), ['Close', 'Volume']]

NameError: ignored

# Rolling Operations

<center><img src="images/rolling.gif" alt="Drawing" style="width: 75%;"/></center>

In [ ]:
aapl.rolling(5)[['Close', 'Adj Close']].mean().plot();

In [ ]:
apple.rolling(5)[['Close', 'Adj Close']].mean().plot();

In [ ]:
# Drop `Volume`, since it's way bigger than everything else.
aapl.drop('Volume', axis=1).resample('2W').max().plot();

In [ ]:
apple.drop('Volume', axis=1).resample('3W').max().plot();

In [ ]:
# 30-day rolling exponentially-weighted stddev of returns.
aapl['Close'].pct_change().ewm(span=30).std().plot();

In [ ]:
apple['Close'].pct_change().ewm(span=10).std().plot();

# "Real World" Data

In [180]:
from demos.avocados import read_avocadata

avocados = read_avocadata('2014', '2016')
avocados.head()

ModuleNotFoundError: ignored

In [181]:
aguacates = read_avocadata('2015', '2016')
aguacates.head()

NameError: ignored

In [186]:
# Unlike numpy arrays, pandas DataFrames can have a different dtype for each column.
avocados.dtypes

NameError: ignored

In [187]:
aguacate.dtypes

NameError: ignored

In [188]:
# What's the regional average price of a HASS avocado every day?
hass = avocados[avocados.Variety == 'HASS']
hass.groupby(['Date', 'Region'])['Weighted Avg Price'].mean().unstack().ffill().plot();

NameError: ignored

In [189]:
aguacateHass = aguacate[avocados.Variety == 'HASS']
aguacateHass.groupby(['Date', 'Region'])['Weighted Avg Price'].mean().unstack().ffill().plot();

NameError: ignored

In [184]:
def _organic_spread(group):

    if len(group.columns) != 2:
        return pd.Series(index=group.index, data=0.0)
    
    is_organic = group.columns.get_level_values('Organic').values.astype(bool)
    organics = group.loc[:, is_organic].squeeze()
    non_organics = group.loc[:, ~is_organic].squeeze()
    diff = organics - non_organics
    return diff

def organic_spread_by_region(df):
    """What's the difference between the price of an organic 
    and non-organic avocado within each region?
    """
    return (
        df
        .set_index(['Date', 'Region', 'Organic'])
         ['Weighted Avg Price']
        .unstack(level=['Region', 'Organic'])
        .ffill()
        .groupby(level='Region', axis=1)
        .apply(_organic_spread)
    )

In [185]:
organic_spread_by_region(hass).plot();
plt.gca().set_title("Daily Regional Organic Spread");
plt.legend(bbox_to_anchor=(1, 1));

NameError: ignored

In [190]:
organic_spread_by_region(aguacateHass).plot();
plt.gca().set_title("Desarrollo");
plt.legend(bbox_to_anchor=(1, 1));

NameError: ignored

In [191]:
spread_correlation = organic_spread_by_region(hass).corr()
spread_correlation

NameError: ignored

In [192]:
esparcimientoRelation = organic_spread_by_region(aguacateHass).corr()
esparcimientoRelation

NameError: ignored

In [ ]:
import seaborn as sns
grid = sns.clustermap(spread_correlation, annot=True)
fig = grid.fig
axes = fig.axes
ax = axes[2]
ax.set_xticklabels(ax.get_xticklabels(), rotation=45);

In [ ]:
malla = sns.clustermap(esparcimientoRelacion, annot=True)
higo = malla.higo
hachas = higo.hachas
hacha = hachas[2]
hacha.set_xticklabels(hacha.get_xticklabels(), rotation=45);

# Pandas Review

- Pandas extends numpy with more complex datastructures and algorithms.
- If you understand numpy, you understand 90% of pandas.
- `groupby`, `set_index`, and `unstack` are powerful tools for working with categorical data.
- Avocado prices are surprisingly interesting :)

# Thanks!