In [1]:
!pip install -U fortran-magic
%matplotlib inline
%load_ext fortranmagic

import sys; sys.path.append('..')

import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

mpl.rc('figure', figsize=(12, 7))

ran_the_first_cell = True

jan2017 = pd.to_datetime(['2017-01-03 00:00:00+00:00',
 '2017-01-04 00:00:00+00:00',
 '2017-01-05 00:00:00+00:00',
 '2017-01-06 00:00:00+00:00',
 '2017-01-09 00:00:00+00:00',
 '2017-01-10 00:00:00+00:00',
 '2017-01-11 00:00:00+00:00',
 '2017-01-12 00:00:00+00:00',
 '2017-01-13 00:00:00+00:00',
 '2017-01-17 00:00:00+00:00',
 '2017-01-18 00:00:00+00:00',
 '2017-01-19 00:00:00+00:00',
 '2017-01-20 00:00:00+00:00',
 '2017-01-23 00:00:00+00:00',
 '2017-01-24 00:00:00+00:00',
 '2017-01-25 00:00:00+00:00',
 '2017-01-26 00:00:00+00:00',
 '2017-01-27 00:00:00+00:00',
 '2017-01-30 00:00:00+00:00',
 '2017-01-31 00:00:00+00:00',
 '2017-02-01 00:00:00+00:00'])
calendar = jan2017.values.astype('datetime64[D]')

event_dates = pd.to_datetime(['2017-01-06 00:00:00+00:00', 
                             '2017-01-07 00:00:00+00:00', 
                             '2017-01-08 00:00:00+00:00']).values.astype('datetime64[D]')
event_values = np.array([10, 15, 20])

Requirement already up-to-date: fortran-magic in /usr/local/lib/python3.6/dist-packages (0.7)


/usr/local/lib/python3.6/dist-packages/fortranmagic.py:147: UserWarning: get_ipython_cache_dir has moved to the IPython.paths module since IPython 4.0.
  self._lib_dir = os.path.join(get_ipython_cache_dir(), 'fortran')


/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


<center>
  <h1>The PyData Toolbox</h1>
  <h3>Scott Sanderson (Twitter: @scottbsanderson, GitHub: ssanderson)</h3>
  <h3><a href="https://github.com/ssanderson/pydata-toolbox">https://github.com/ssanderson/pydata-toolbox</a></h3>
</center>

# About Me:

<img src="images/me.jpg" alt="Drawing" style="width: 300px;"/>

- Senior Engineer at [Quantopian](www.quantopian.com)
- Background in Mathematics and Philosophy
- **Twitter:** [@scottbsanderson](https://twitter.com/scottbsanderson)
- **GitHub:** [ssanderson](github.com/ssanderson)

## Outline

- Built-in Data Structures
- Numpy `array`
- Pandas `Series`/`DataFrame`
- Plotting and "Real-World" Analyses

# Data Structures

> Rule 5. Data dominates. If you've chosen the right data structures and organized things well, the algorithms
will almost always be self-evident. Data structures, not algorithms, are central to programming.

- *Notes on Programming in C*, by Rob Pike.

# Lists

In [2]:
%reload_ext fortranmagic
assert ran_the_first_cell, "Oh noes!"

/usr/local/lib/python3.6/dist-packages/fortranmagic.py:147: UserWarning: get_ipython_cache_dir has moved to the IPython.paths module since IPython 4.0.
  self._lib_dir = os.path.join(get_ipython_cache_dir(), 'fortran')


In [3]:
assert ran_the_first_cell, "Hey "

In [4]:
l = [1, 'two', 3.0, 4, 5.0, "six"]
l

[1, 'two', 3.0, 4, 5.0, 'six']

In [5]:
l1 = [1, 'two', 3.0, 4, 5.0, "six", 6, 5, 4,3,True]
l1

[1, 'two', 3.0, 4, 5.0, 'six', 6, 5, 4, 3, True]

In [6]:
# Lists can be indexed like C-style arrays.
first = l[0]
second = l[1]
print("first:", first)
print("second:", second)

first: 1
second: two


In [7]:
primero = l1[0]
segundo = l1[1]
print("primero:", primero)
print("segundo:", segundo)

primero: 1
segundo: two


In [8]:
# Negative indexing gives elements relative to the end of the list.
last = l[-1]
penultimate = l[-2]
print("last:", last)
print("second to last:", penultimate)

last: six
second to last: 5.0


In [9]:
ultimo = l1[-1]
penultimo = l1[-2]
print("ultimo:", ultimo)
print("penultimo :", penultimo)

ultimo: True
penultimo : 3


In [10]:
# Lists can also be sliced, which makes a copy of elements between 
# start (inclusive) and stop (exclusive)
sublist = l[1:3]
sublist

['two', 3.0]

In [11]:
sublista = l1[1:5]
sublista

['two', 3.0, 4, 5.0]

In [12]:
# l[:N] is equivalent to l[0:N].
first_three = l[:3]
first_three

[1, 'two', 3.0]

In [13]:
primerosTres = l1[:3]
primerosTres

[1, 'two', 3.0]

In [14]:
# l[3:] is equivalent to l[3:len(l)].
after_three = l[3:]
after_three

[4, 5.0, 'six']

In [15]:
despues_Cuatro= l1[4:]
despues_Cuatro

[5.0, 'six', 6, 5, 4, 3, True]

In [16]:
# There's also a third parameter, "step", which gets every Nth element.
l = ['a', 'b', 'c', 'd', 'e', 'f', 'g','h']
l[1:7:2]

['b', 'd', 'f']

In [17]:
l1 = ['<', 'z', 'x', 'c', 'v', 'b', 'n','m']
l1[1:7:2]

['z', 'c', 'b']

In [18]:
# This is a cute way to reverse a list.
l[::-1]

['h', 'g', 'f', 'e', 'd', 'c', 'b', 'a']

In [19]:
l1[::-1]

['m', 'n', 'b', 'v', 'c', 'x', 'z', '<']

In [20]:
# Lists can be grown efficiently (in O(1) amortized time).
l = [1, 2, 3, 4, 5]
print("Before:", l)
l.append('six')
print("After:", l)

Before: [1, 2, 3, 4, 5]
After: [1, 2, 3, 4, 5, 'six']


In [21]:
l1 = [9, 8, 7,6, 5]
print("Antes:", l1)
l1.append('4')
print("Despues:", l1)

Antes: [9, 8, 7, 6, 5]
Despues: [9, 8, 7, 6, 5, '4']


In [22]:
# Comprehensions let us perform elementwise computations.
l = [1, 2, 3, 4, 5]
[x * 2 for x in l]

[2, 4, 6, 8, 10]

In [23]:
l1 = [2, 4, 6, 8]
[x * 2 for x in l1]

[4, 8, 12, 16]

## Review: Python Lists

- Zero-indexed sequence of arbitrary Python values.
- Slicing syntax: `l[start:stop:step]` copies elements at regular intervals from `start` to `stop`.
- Efficient (`O(1)`) appends and removes from end.
- Comprehension syntax: `[f(x) for x in l if cond(x)]`.

# Dictionaries

In [24]:
# Dictionaries are key-value mappings.
philosophers = {'David': 'Hume', 'Immanuel': 'Kant', 'Bertrand': 'Russell'}
philosophers

{'Bertrand': 'Russell', 'David': 'Hume', 'Immanuel': 'Kant'}

In [25]:
personas = {'Dud': 'Hume', 'Dud1': 'Kant', 'dud2': 'Russell'}
personas

{'Dud': 'Hume', 'Dud1': 'Kant', 'dud2': 'Russell'}

In [26]:
# Like lists, dictionaries are size-mutable.
philosophers['Ludwig'] = 'Wittgenstein'
philosophers

{'Bertrand': 'Russell',
 'David': 'Hume',
 'Immanuel': 'Kant',
 'Ludwig': 'Wittgenstein'}

In [27]:
personas['dud3']= 'warap1'
personas

{'Dud': 'Hume', 'Dud1': 'Kant', 'dud2': 'Russell', 'dud3': 'warap1'}

In [28]:
del philosophers['David']
philosophers

{'Bertrand': 'Russell', 'Immanuel': 'Kant', 'Ludwig': 'Wittgenstein'}

In [29]:
del personas['Dud']
personas

{'Dud1': 'Kant', 'dud2': 'Russell', 'dud3': 'warap1'}

In [30]:
# No slicing.
# philosophers['Bertrand':'Immanuel']

## Review: Python Dictionaries

- Unordered key-value mapping from (almost) arbitrary keys to arbitrary values.
- Efficient (`O(1)`) lookup, insertion, and deletion.
- No slicing (would require a notion of order).

<center><img src="images/pacino.gif" alt="Drawing" style="width: 100%;"/></center>


In [31]:
# Suppose we have some matrices...
a = [[1, 2, 3],
     [2, 3, 4],
     [5, 6, 7],
     [1, 1, 1]]

b = [[1, 2, 3, 4],
     [2, 3, 4, 5]]

In [32]:
a1 = [[1, 2, 3],
     [2, 3, 4],
     [5, 6, 7],
     [0, 0, 0]]

b1 = [[1, 2, 3, 1],
     [2, 3, 4, 1]]

In [33]:
def matmul(A, B):
    """Multiply matrix A by matrix B."""
    rows_out = len(A)
    cols_out = len(B[0])
    out = [[0 for col in range(cols_out)] for row in range(rows_out)]
    
    for i in range(rows_out):
        for j in range(cols_out):
            for k in range(len(B)):
                out[i][j] += A[i][k] * B[k][j]
    return out

<center><img src="images/gross.gif" alt="Drawing" style="width: 50%;"/></center>


In [34]:
%%time

matmul(a, b)

CPU times: user 28 µs, sys: 5 µs, total: 33 µs
Wall time: 37.4 µs


[[5, 8, 11, 14], [8, 13, 18, 23], [17, 28, 39, 50], [3, 5, 7, 9]]

In [35]:
matmul(a1,b1)

[[5, 8, 11, 3], [8, 13, 18, 5], [17, 28, 39, 11], [0, 0, 0, 0]]

In [36]:
import random
def random_matrix(m, n):
    out = []
    for row in range(m):
        out.append([random.random() for _ in range(n)])
    return out

randm = random_matrix(2, 3)
randm

[[0.9559905283907445, 0.5677607180611235, 0.4134616917204764],
 [0.9329741499493178, 0.38945529004750357, 0.09739167329741771]]

In [37]:
def random_matriz(m, n):
    salida = []
    for fila in range(m):
        salida.append([random.random() for _ in range(n)])
    return salida

randm1 = random_matrix(2, 3)
randm1

[[0.7932487249853497, 0.16268467864816216, 0.5458802801375024],
 [0.25932265912013264, 0.8420458177994632, 0.6876786021264369]]

In [38]:
%%time
randa = random_matrix(600, 100)
randb = random_matrix(100, 600)
x = matmul(randa, randb)

CPU times: user 6.89 s, sys: 22.6 ms, total: 6.92 s
Wall time: 6.93 s


In [39]:
randa1 = random_matriz(600, 300)
randb1 = random_matriz(300, 600)
x1 = matmul(randa1, randb1)

In [40]:
def python_dot_product(xs, ys):
    return sum(x * y for x, y in zip(xs, ys))

In [41]:
# Maybe that's not that bad?  Let's try a simpler case.
def python_dot_product1(xs1, ys1):
    return sum(x * y for x, y in zip(xs1, ys1))

In [42]:
%%fortran
subroutine fortran_dot_product(xs, ys, result)
    double precision, intent(in) :: xs(:)
    double precision, intent(in) :: ys(:)
    double precision, intent(out) :: result
    
    result = sum(xs * ys)
end

In [43]:
%%fortran
subroutine fortran_dot_product1(xs1, ys1, resultado)
    double precision, intent(in) :: xs1(:)
    double precision, intent(in) :: ys1(:)
    double precision, intent(out) :: resultado
    
    result = sum(xs1 * ys1)
end

In [44]:
list_data = [float(i) for i in range(100000)]
array_data = np.array(list_data)

In [45]:
listaDatos = [float(i) for i in range(100000)]
arrayDatos = np.array(listaDatos)

In [46]:
%%time
python_dot_product(list_data, list_data)

CPU times: user 11.6 ms, sys: 8 µs, total: 11.6 ms
Wall time: 11.5 ms


333328333350000.0

In [47]:
%%time
python_dot_product1(listaDatos, listaDatos)

CPU times: user 8.45 ms, sys: 992 µs, total: 9.45 ms
Wall time: 9.9 ms


333328333350000.0

In [48]:
%%time
fortran_dot_product(array_data, array_data)

CPU times: user 182 µs, sys: 3 µs, total: 185 µs
Wall time: 190 µs


333328333350000.0

In [49]:
%%time
fortran_dot_product1(arrayDatos, arrayDatos)

CPU times: user 10 µs, sys: 0 ns, total: 10 µs
Wall time: 14.3 µs


0.0

<center><img src="images/sloth.gif" alt="Drawing" style="width: 1080px;"/></center>


## Why is the Python Version so Much Slower?

In [50]:
# Dynamic typing.
def mul_elemwise(xs, ys):
    return [x * y for x, y in zip(xs, ys)]

mul_elemwise([1, 2, 3, 4], [1, 2 + 0j, 3.0, 'four'])
#[type(x) for x in _]

[1, (4+0j), 9.0, 'fourfourfourfour']

In [51]:
def mulElemwise1(xs1, ys1):
    return [x * y for x, y in zip(xs1, ys1)]

mulElemwise1([1, 2, 3, 4], [1, 2 + 0j, 3.0, 'four'])

[1, (4+0j), 9.0, 'fourfourfourfour']

In [52]:
# Interpretation overhead.
source_code = 'a + b * c'
bytecode = compile(source_code, '', 'eval')
import dis; dis.dis(bytecode)

  1           0 LOAD_NAME                0 (a)
              2 LOAD_NAME                1 (b)
              4 LOAD_NAME                2 (c)
              6 BINARY_MULTIPLY
              8 BINARY_ADD
             10 RETURN_VALUE


In [53]:
sourceCodigo = 'a1 + b1 * c1'
byteCodigo = compile(sourceCodigo, '', 'eval')
import dis; dis.dis(byteCodigo)

  1           0 LOAD_NAME                0 (a1)
              2 LOAD_NAME                1 (b1)
              4 LOAD_NAME                2 (c1)
              6 BINARY_MULTIPLY
              8 BINARY_ADD
             10 RETURN_VALUE


## Why is the Python Version so Slow?
- Dynamic typing means that every single operation requires dispatching on the input type.
- Having an interpreter means that every instruction is fetched and dispatched at runtime.
- Other overheads:
  - Arbitrary-size integers.
  - Reference-counted garbage collection.

> This is the paradox that we have to work with when we're doing scientific or numerically-intensive Python. What makes Python fast for development -- this high-level, interpreted, and dynamically-typed aspect of the language -- is exactly what makes it slow for code execution.

- Jake VanderPlas, [*Losing Your Loops: Fast Numerical Computing with NumPy*](https://www.youtube.com/watch?v=EEUXKG97YRw)

# What Do We Do?

<center><img src="images/runaway.gif" alt="Drawing" style="width: 50%;"/></center>

<center><img src="images/thisisfine.gif" alt="Drawing" style="width: 1080px;"/></center>

- Python is slow for numerical computation because it performs dynamic dispatch on every operation we perform...

- ...but often, we just want to do the same thing over and over in a loop!

- If we don't need Python's dynamicism, we don't want to pay (much) for it.

- **Idea:** Dispatch **once per operation** instead of **once per element**.

In [54]:
import numpy as np

data = np.array([1, 2, 3, 4])
data

array([1, 2, 3, 4])

In [55]:
datos = np.array([1, 2, 3, 4])
datos

array([1, 2, 3, 4])

In [56]:
data + data

array([2, 4, 6, 8])

In [57]:
datos + datos

array([2, 4, 6, 8])

In [58]:
%%time
# Naive dot product
(array_data * array_data).sum()

CPU times: user 74 µs, sys: 1 ms, total: 1.07 ms
Wall time: 1.5 ms


333328333350000.0

In [59]:
%%time
(arrayDatos * arrayDatos).sum()

CPU times: user 512 µs, sys: 0 ns, total: 512 µs
Wall time: 816 µs


333328333350000.0

In [60]:
%%time
array_data.dot(arrayDatos)

CPU times: user 1.33 ms, sys: 2.97 ms, total: 4.31 ms
Wall time: 5.39 ms


333328333350000.0

In [61]:
%%time
fortran_dot_product(array_data, array_data)

CPU times: user 195 µs, sys: 0 ns, total: 195 µs
Wall time: 203 µs


333328333350000.0

In [62]:
%%time
fortran_dot_product1(array_data, arrayDatos)

CPU times: user 11 µs, sys: 0 ns, total: 11 µs
Wall time: 15 µs


0.0

In [63]:
# Numpy won't allow us to write a string into an int array.
#data[0] = "foo"

In [64]:
# We also can't grow an array once it's created.
#data.append(3)

In [65]:
# We **can** reshape an array though.
two_by_two = data.reshape(2, 2)
two_by_two

array([[1, 2],
       [3, 4]])

In [66]:
dos_por_dos = datos.reshape(2, 2)
dos_por_dos

array([[1, 2],
       [3, 4]])

Numpy arrays are:

- Fixed-type

- Size-immutable

- Multi-dimensional

- Fast\*

\* If you use them correctly.

# What's in an Array?

In [67]:
arr = np.array([1, 2, 3, 4, 5, 6], dtype='int16').reshape(2, 3)
print("Array:\n", arr, sep='')
print("===========")
print("DType:", arr.dtype)
print("Shape:", arr.shape)
print("Strides:", arr.strides)
print("Data:", arr.data.tobytes())

Array:
[[1 2 3]
 [4 5 6]]
DType: int16
Shape: (2, 3)
Strides: (6, 2)
Data: b'\x01\x00\x02\x00\x03\x00\x04\x00\x05\x00\x06\x00'


In [68]:
arr1 = np.array([1, 0, 0, 1, 0, 0], dtype='int32').reshape(2, 3)

print("DType:", arr1.dtype)
print("Shape:", arr1.shape)
print("Strides:", arr1.strides)
print("Data:", arr1.data.tobytes())

DType: int32
Shape: (2, 3)
Strides: (12, 4)
Data: b'\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'


# Core Operations

- Vectorized **ufuncs** for elementwise operations.
- Fancy indexing and masking for selection and filtering.
- Aggregations across axes.
- Broadcasting

# UFuncs

UFuncs (universal functions) are functions that operate elementwise on one or more arrays.

In [69]:
data = np.arange(15).reshape(3, 5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [70]:
datos = np.arange(15).reshape(5, 3)
datos

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [71]:
# Binary operators.
data * data

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196]])

In [72]:
datos * datos

array([[  0,   1,   4],
       [  9,  16,  25],
       [ 36,  49,  64],
       [ 81, 100, 121],
       [144, 169, 196]])

In [73]:
# Unary functions.
np.sqrt(data)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739]])

In [74]:
np.sqrt(datos)


array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479],
       [3.46410162, 3.60555128, 3.74165739]])

In [75]:
# Comparison operations
(data % 3) == 0

array([[ True, False, False,  True, False],
       [False,  True, False, False,  True],
       [False, False,  True, False, False]])

In [76]:
(datos % 2) == 0

array([[ True, False,  True],
       [False,  True, False],
       [ True, False,  True],
       [False,  True, False],
       [ True, False,  True]])

In [77]:
# Boolean combinators.
((data % 2) == 0) & ((data % 3) == 0)

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False]])

In [78]:
((datos % 4) == 0) & ((datos % 6) == 0)

array([[ True, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [ True, False, False]])

In [79]:
# as of python 3.5, @ is matrix-multiply
data @ data.T

array([[ 30,  80, 130],
       [ 80, 255, 430],
       [130, 430, 730]])

In [80]:
datos @ datos.T

array([[  5,  14,  23,  32,  41],
       [ 14,  50,  86, 122, 158],
       [ 23,  86, 149, 212, 275],
       [ 32, 122, 212, 302, 392],
       [ 41, 158, 275, 392, 509]])

# UFuncs Review

- UFuncs provide efficient elementwise operations applied across one or more arrays.
- Arithmetic Operators (`+`, `*`, `/`)
- Comparisons (`==`, `>`, `!=`)
- Boolean Operators (`&`, `|`, `^`)
- Trigonometric Functions (`sin`, `cos`)
- Transcendental Functions (`exp`, `log`)

# Selections

We often want to perform an operation on just a subset of our data.

In [81]:
sines = np.sin(np.linspace(0, 3.14, 10))
cosines = np.cos(np.linspace(0, 3.14, 10))
sines

array([0.        , 0.34185385, 0.64251645, 0.86575984, 0.98468459,
       0.98496101, 0.8665558 , 0.64373604, 0.34335012, 0.00159265])

In [82]:
senos = np.sin(np.linspace(0, 3.14, 10))
cosenos = np.cos(np.linspace(0, 3.14, 10))
senos

array([0.        , 0.34185385, 0.64251645, 0.86575984, 0.98468459,
       0.98496101, 0.8665558 , 0.64373604, 0.34335012, 0.00159265])

In [83]:
# Slicing works with the same semantics as Python lists.
sines[0]

0.0

In [84]:
senos[0]

0.0

In [85]:
sines[:3]  # First three elements  

array([0.        , 0.34185385, 0.64251645])

In [86]:
senos[1:4]

array([0.34185385, 0.64251645, 0.86575984])

In [87]:
sines[5:]  # Elements from 5 on.

array([0.98496101, 0.8665558 , 0.64373604, 0.34335012, 0.00159265])

In [88]:
senos[1:4]

array([0.34185385, 0.64251645, 0.86575984])

In [89]:
sines[::2]  # Every other element.

array([0.        , 0.64251645, 0.98468459, 0.8665558 , 0.34335012])

In [90]:
senos[::2]

array([0.        , 0.64251645, 0.98468459, 0.8665558 , 0.34335012])

In [91]:
# More interesting: we can index with boolean arrays to filter by a predicate.
print("sines:\n", sines)
print("sines > 0.5:\n", sines > 0.5)
print("sines[sines > 0.5]:\n", sines[sines > 0.5])

sines:
 [0.         0.34185385 0.64251645 0.86575984 0.98468459 0.98496101
 0.8665558  0.64373604 0.34335012 0.00159265]
sines > 0.5:
 [False False  True  True  True  True  True  True False False]
sines[sines > 0.5]:
 [0.64251645 0.86575984 0.98468459 0.98496101 0.8665558  0.64373604]


In [92]:
print("senos:\n", senos)
print("senos > 0.5:\n", senos > 0.5)
print("senos[senos > 0.5]:\n", senos[senos > 0.5])

senos:
 [0.         0.34185385 0.64251645 0.86575984 0.98468459 0.98496101
 0.8665558  0.64373604 0.34335012 0.00159265]
senos > 0.5:
 [False False  True  True  True  True  True  True False False]
senos[senos > 0.5]:
 [0.64251645 0.86575984 0.98468459 0.98496101 0.8665558  0.64373604]


In [93]:
# We index with lists/arrays of integers to select values at those indices.
print(sines)
sines[[0, 4, 7]]

[0.         0.34185385 0.64251645 0.86575984 0.98468459 0.98496101
 0.8665558  0.64373604 0.34335012 0.00159265]


array([0.        , 0.98468459, 0.64373604])

In [94]:
print(senos)
senos[[0, 4, 7]]

[0.         0.34185385 0.64251645 0.86575984 0.98468459 0.98496101
 0.8665558  0.64373604 0.34335012 0.00159265]


array([0.        , 0.98468459, 0.64373604])

In [95]:
# Index arrays are often used for sorting one or more arrays.
unsorted_data = np.array([1, 3, 2, 12, -1, 5, 2])

In [96]:
desordenados_datos = np.array([1, 3, 1, 2, 5, 14])

In [97]:
sort_indices = np.argsort(unsorted_data)
sort_indices

array([4, 0, 2, 6, 1, 5, 3])

In [98]:
ordenar_indices = np.argsort(desordenados_datos)
ordenar_indices

array([0, 2, 3, 1, 4, 5])

In [99]:
unsorted_data[sort_indices]

array([-1,  1,  2,  2,  3,  5, 12])

In [100]:
desordenados_datos[ordenar_indices]

array([ 1,  1,  2,  3,  5, 14])

In [101]:
market_caps = np.array([12, 6, 10, 5, 6])  # Presumably in dollars?
assets = np.array(['A', 'B', 'C', 'D', 'E'])

In [102]:
mercado_capitulo = np.array([15, 6, 11 , 5, 6])  
bienes = np.array(['A', 'B', 'C', 'D', 'E'])

In [103]:
# Sort assets by market cap by using the permutation that would sort market caps on ``assets``.
sort_by_mcap = np.argsort(market_caps)
assets[sort_by_mcap]

array(['D', 'B', 'E', 'C', 'A'], dtype='<U1')

In [104]:
ordenar_por_mcap = np.argsort(mercado_capitulo)
bienes[ordenar_por_mcap]

array(['D', 'B', 'E', 'C', 'A'], dtype='<U1')

In [105]:
# Indexers are also useful for aligning data.
print("Dates:\n", repr(event_dates))
print("Values:\n", repr(event_values))
print("Calendar:\n", repr(calendar))

Dates:
 array(['2017-01-06', '2017-01-07', '2017-01-08'], dtype='datetime64[D]')
Values:
 array([10, 15, 20])
Calendar:
 array(['2017-01-03', '2017-01-04', '2017-01-05', '2017-01-06',
       '2017-01-09', '2017-01-10', '2017-01-11', '2017-01-12',
       '2017-01-13', '2017-01-17', '2017-01-18', '2017-01-19',
       '2017-01-20', '2017-01-23', '2017-01-24', '2017-01-25',
       '2017-01-26', '2017-01-27', '2017-01-30', '2017-01-31',
       '2017-02-01'], dtype='datetime64[D]')


In [106]:
print("Datos:\n", repr(event_dates))
print("Valores:\n", repr(event_values))
print("Calendario:\n", repr(calendar))

Datos:
 array(['2017-01-06', '2017-01-07', '2017-01-08'], dtype='datetime64[D]')
Valores:
 array([10, 15, 20])
Calendario:
 array(['2017-01-03', '2017-01-04', '2017-01-05', '2017-01-06',
       '2017-01-09', '2017-01-10', '2017-01-11', '2017-01-12',
       '2017-01-13', '2017-01-17', '2017-01-18', '2017-01-19',
       '2017-01-20', '2017-01-23', '2017-01-24', '2017-01-25',
       '2017-01-26', '2017-01-27', '2017-01-30', '2017-01-31',
       '2017-02-01'], dtype='datetime64[D]')


In [107]:
print("Raw Dates:", event_dates)
print("Indices:", calendar.searchsorted(event_dates))
print("Forward-Filled Dates:", calendar[calendar.searchsorted(event_dates)])

Raw Dates: ['2017-01-06' '2017-01-07' '2017-01-08']
Indices: [3 4 4]
Forward-Filled Dates: ['2017-01-06' '2017-01-09' '2017-01-09']


In [108]:
print("fechas:", event_dates)
print("Indices:", calendar.searchsorted(event_dates))
print("Fechas citas:", calendar[calendar.searchsorted(event_dates)])

fechas: ['2017-01-06' '2017-01-07' '2017-01-08']
Indices: [3 4 4]
Fechas citas: ['2017-01-06' '2017-01-09' '2017-01-09']


On multi-dimensional arrays, we can slice along each axis independently.

In [109]:
data = np.arange(25).reshape(5, 5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [110]:
datos = np.arange(25).reshape(5, 5)
datos

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [111]:
data[:2, :2]  # First two rows and first two columns.

array([[0, 1],
       [5, 6]])

In [112]:
datos[:2, :2]

array([[0, 1],
       [5, 6]])

In [113]:
data[:2, [0, -1]]  # First two rows, first and last columns.

array([[0, 4],
       [5, 9]])

In [114]:
datos[:2, [0, -1]]

array([[0, 4],
       [5, 9]])

In [115]:
data[(data[:, 0] % 2) == 0]  # Rows where the first column is divisible by two.

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [116]:
datos[(datos[:, 0] % 2) == 0]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

# Selections Review

- Indexing with an integer removes a dimension.
- Slicing operations work on Numpy arrays the same way they do on lists.
- Indexing with a boolean array filters to True locations.
- Indexing with an integer array selects indices along an axis.
- Multidimensional arrays can apply selections independently along different axes.

## Reductions

Functions that reduce an array to a scalar.

$Var(X) = \frac{1}{N}\sqrt{\sum_{i=1}^N (x_i - \bar{x})^2}$

In [117]:
def variance(x):
    return ((x - x.mean()) ** 2).sum() / len(x)

In [118]:
def varianza(x1):
    return ((x1 - x1.mean()) ** 2).sum() / len(x1)

In [119]:
variance(np.random.standard_normal(1000))

0.970963629118113

In [120]:
varianza(np.random.standard_normal(1000))

1.040585640945998

- `sum()` and `mean()` are both **reductions**.

- In the simplest case, we use these to reduce an entire array into a single value...

In [121]:
data = np.arange(30)
data.mean()

14.5

In [122]:
datos = np.arange(30)
datos.mean()

14.5

- ...but we can do more interesting things with multi-dimensional arrays.

In [123]:
data = np.arange(30).reshape(3, 10)
data

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [124]:
datos = np.arange(30).reshape(3, 10)
datos

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [125]:
data.mean()

14.5

In [126]:
datos.mean()

14.5

In [127]:
data.mean(axis=0)

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19.])

In [128]:
datos.mean(axis=0)

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19.])

In [129]:
data.mean(axis=1)

array([ 4.5, 14.5, 24.5])

In [130]:
datos.mean(axis=1)

array([ 4.5, 14.5, 24.5])

## Reductions Review

- Reductions allow us to perform efficient aggregations over arrays.
- We can do aggregations over a single axis to collapse a single dimension.
- Many built-in reductions (`mean`, `sum`, `min`, `max`, `median`, ...).

# Broadcasting

In [131]:
row = np.array([1, 2, 3, 4])
column = np.array([[1], [2], [3]])
print("Row:\n", row, sep='')
print("Column:\n", column, sep='')

Row:
[1 2 3 4]
Column:
[[1]
 [2]
 [3]]


In [132]:
fila = np.array([1, 2, 3, 4])
columna = np.array([[1], [2], [3]])
print("fila:\n", fila, sep='')
print("Columna:\n", columna, sep='')

fila:
[1 2 3 4]
Columna:
[[1]
 [2]
 [3]]


In [133]:
row + column

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

In [134]:
fila + columna

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

<center><img src="images/broadcasting.png" alt="Drawing" style="width: 60%;"/></center>

<h5>Source: http://www.scipy-lectures.org/_images/numpy_broadcasting.png</h5>

In [135]:
# Broadcasting is particularly useful in conjunction with reductions.
print("Data:\n", data, sep='')
print("Mean:\n", data.mean(axis=0), sep='')
print("Data - Mean:\n", data - data.mean(axis=0), sep='')

Data:
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]
Mean:
[10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
Data - Mean:
[[-10. -10. -10. -10. -10. -10. -10. -10. -10. -10.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [ 10.  10.  10.  10.  10.  10.  10.  10.  10.  10.]]


In [136]:
print("Datos:\n", data, sep='')
print("Media:\n", data.mean(axis=0), sep='')
print("Datos - Media:\n", datos - datos.mean(axis=0), sep='')

Datos:
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]
Media:
[10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
Datos - Media:
[[-10. -10. -10. -10. -10. -10. -10. -10. -10. -10.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [ 10.  10.  10.  10.  10.  10.  10.  10.  10.  10.]]


# Broadcasting Review

- Numpy operations can work on arrays of different dimensions as long as the arrays' shapes are still "compatible".
- Broadcasting works by "tiling" the smaller array along the missing dimension.
- The result of a broadcasted operation is always at least as large in each dimension as the largest array in that dimension.

# Numpy Review

- Numerical algorithms are slow in pure Python because the overhead dynamic dispatch dominates our runtime.

- Numpy solves this problem by:
  1. Imposing additional restrictions on the contents of arrays.
  2. Moving the inner loops of our algorithms into compiled C code.

- Using Numpy effectively often requires reworking an algorithms to use vectorized operations instead of for-loops, but the resulting operations are usually simpler, clearer, and faster than the pure Python equivalent.

<center><img src="images/unicorn.jpg" alt="Drawing" style="width: 75%;"/></center>

Numpy is great for many things, but...

- Sometimes our data is equipped with a natural set of **labels**:
  - Dates/Times
  - Stock Tickers
  - Field Names (e.g. Open/High/Low/Close)

- Sometimes we have **more than one type of data** that we want to keep grouped together.
  - Tables with a mix of real-valued and categorical data.

- Sometimes we have **missing** data, which we need to ignore, fill, or otherwise work around.

<center><img src="images/panda-wrangling.gif" alt="Drawing" style="width: 75%;"/></center>

<center><img src="images/pandas_logo.png" alt="Drawing" style="width: 75%;"/></center>


Pandas extends Numpy with more complex data structures:

- `Series`: 1-dimensional, homogenously-typed, labelled array.
- `DataFrame`: 2-dimensional, semi-homogenous, labelled table.

Pandas also provides many utilities for: 
- Input/Output
- Data Cleaning
- Rolling Algorithms
- Plotting

# Selection in Pandas

In [137]:
s = pd.Series(index=['a', 'b', 'c', 'd', 'e'], data=[1, 2, 3, 4, 5])
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [138]:
s1 = pd.Series(index=['aa', 'b1', 'cd', 'de', 'ef'], data=[1, 2, 3, 4, 5])
s1

aa    1
b1    2
cd    3
de    4
ef    5
dtype: int64

In [139]:
# There are two pieces to a Series: the index and the values.
print("The index is:", s.index)
print("The values are:", s.values)

The index is: Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
The values are: [1 2 3 4 5]


In [140]:
print("The index is:", s1.index)
print("The values are:", s1.values)

The index is: Index(['aa', 'b1', 'cd', 'de', 'ef'], dtype='object')
The values are: [1 2 3 4 5]


In [141]:
# We can look up values out of a Series by position...
s.iloc[0]

1

In [142]:
s1.iloc[0]

1

In [143]:
# ... or by label.
s.loc['a']

1

In [144]:
s1.loc['aa']

1

In [145]:
# Slicing works as expected...
s.iloc[:2]

a    1
b    2
dtype: int64

In [146]:
s1.iloc[:2]

aa    1
b1    2
dtype: int64

In [147]:
# ...but it works with labels too!
s.loc[:'c']

a    1
b    2
c    3
dtype: int64

In [148]:
s1.loc[:'cd']

aa    1
b1    2
cd    3
dtype: int64

In [149]:
# Fancy indexing works the same as in numpy.
s.iloc[[0, -1]]

a    1
e    5
dtype: int64

In [150]:
s1.iloc[[0, -1]]

aa    1
ef    5
dtype: int64

In [151]:
# As does boolean masking.
s.loc[s > 2]

c    3
d    4
e    5
dtype: int64

In [152]:
s1.loc[s1 > 2]

cd    3
de    4
ef    5
dtype: int64

In [153]:
# Element-wise operations are aligned by index.
other_s = pd.Series({'a': 10.0, 'c': 20.0, 'd': 30.0, 'z': 40.0})
other_s

a    10.0
c    20.0
d    30.0
z    40.0
dtype: float64

In [154]:
otro_s1 = pd.Series({'a': 10.0, 'c': 20.0, 'd': 30.0, 'z': 40.0})
otro_s1

a    10.0
c    20.0
d    30.0
z    40.0
dtype: float64

In [155]:
s + other_s

a    11.0
b     NaN
c    23.0
d    34.0
e     NaN
z     NaN
dtype: float64

In [156]:
# We can fill in missing values with fillna().
(s + other_s).fillna(0.0)

a    11.0
b     0.0
c    23.0
d    34.0
e     0.0
z     0.0
dtype: float64

In [157]:
(s1 + otro_s1).fillna(0.1)

a     0.1
aa    0.1
b1    0.1
c     0.1
cd    0.1
d     0.1
de    0.1
ef    0.1
z     0.1
dtype: float64

In [158]:
# Most real datasets are read in from an external file format.
#aapl = pd.read_csv('https://github.com/matplotlib/sample_data/blob/master/aapl.csv', parse_dates=[0])
#aapl.head()

In [159]:
# Slicing generalizes to two dimensions as you'd expect:
#aapl.iloc[:2, :2]

In [160]:
#aapl.loc[pd.Timestamp('2010-02-01'):pd.Timestamp('2010-02-04'), ['Close', 'Volume']]

# Rolling Operations

<center><img src="images/rolling.gif" alt="Drawing" style="width: 75%;"/></center>

In [161]:
#aapl.rolling(5)[['Close', 'Adj Close']].mean().plot();

In [162]:
## Drop `Volume`, since it's way bigger than everything else.
#aapl.drop('Volume', axis=1).resample('2W').max().plot();

In [163]:
# 30-day rolling exponentially-weighted stddev of returns.
#aapl['Close'].pct_change().ewm(span=30).std().plot();

# "Real World" Data

In [164]:
#from demos.avocados import read_avocadata

#avocados = read_avocadata('2014', '2016')
#avocados.head()

In [165]:
# Unlike numpy arrays, pandas DataFrames can have a different dtype for each column.
#avocados.dtypes

In [166]:
# What's the regional average price of a HASS avocado every day?
#hass = avocados[avocados.Variety == 'HASS']
#hass.groupby(['Date', 'Region'])['Weighted Avg Price'].mean().unstack().ffill().plot();

In [167]:
def _organic_spread(group):

    if len(group.columns) != 2:
        return pd.Series(index=group.index, data=0.0)
    
    is_organic = group.columns.get_level_values('Organic').values.astype(bool)
    organics = group.loc[:, is_organic].squeeze()
    non_organics = group.loc[:, ~is_organic].squeeze()
    diff = organics - non_organics
    return diff

def organic_spread_by_region(df):
    """What's the difference between the price of an organic 
    and non-organic avocado within each region?
    """
    return (
        df
        .set_index(['Date', 'Region', 'Organic'])
         ['Weighted Avg Price']
        .unstack(level=['Region', 'Organic'])
        .ffill()
        .groupby(level='Region', axis=1)
        .apply(_organic_spread)
    )

In [168]:
#organic_spread_by_region(hass).plot();
#plt.gca().set_title("Daily Regional Organic Spread");
#plt.legend(bbox_to_anchor=(1, 1));

In [169]:
#spread_correlation = organic_spread_by_region(hass).corr()
#spread_correlation

In [170]:
#import seaborn as sns
#grid = sns.clustermap(spread_correlation, annot=True)
#fig = grid.fig
#axes = fig.axes
#ax = axes[2]
#ax.set_xticklabels(ax.get_xticklabels(), rotation=45);

# Pandas Review

- Pandas extends numpy with more complex datastructures and algorithms.
- If you understand numpy, you understand 90% of pandas.
- `groupby`, `set_index`, and `unstack` are powerful tools for working with categorical data.
- Avocado prices are surprisingly interesting :)

# Thanks!